stages:
  download_graphs:
    cmd: python src/download_graphs.py
    deps:
    - src/download_graphs.py
    outs:
    - data/OSM/CT_drive.graphml
    - data/OSM/CT_walk.graphml
    - data/OSM/MA_drive.graphml
    - data/OSM/MA_walk.graphml
    - data/OSM/ME_drive.graphml
    - data/OSM/ME_walk.graphml
    - data/OSM/NH_drive.graphml
    - data/OSM/NH_walk.graphml
    - data/OSM/RI_drive.graphml
    - data/OSM/RI_walk.graphml
    - data/OSM/VT_drive.graphml
    -  data/OSM/VT_walk.graphml
