name: ox
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - osmnx
  - ipykernel
  - ca-certificates
  - certifi
  - openssl
  - contextily
  - tqdm
  - ipywidgets
  - jupyter
  - seaborn
  - cenpy
  - python-dotenv
  - geopandas
  - dvc
  - dvc-gdrive
